version: '3.7'

services:
  kira:
    environment:
      - KIRA_ENV=$KIRA_ENV
    restart: always
    build: '.'
    container_name: kira
    depends_on:
      - cache
      - database
    ports:
      - 9090:9090
    cap_add:
      - LINUX_IMMUTABLE
      - CAP_SYS_ADMIN
  database:
    image: mongo:latest
    container_name: database
    restart: always
    volumes:
      - ./logs:/data/db
    command: mongod --quiet --logpath /dev/null
  cache:
    image: redis:7.0.5-alpine
    container_name: cache
